[package]
name = "spacegame"
version = "0.1.0"
authors = ["Graham Cox <graham@grahamcox.co.uk>"]
edition = "2018"

[lib]
name = "spacegame_lib"

[[bin]]
name="spacegame"

[dependencies]
dotenv = "0.15.0"
serde = {version = "1.0.105", features=["derive"] }
config = "0.10.1"
env_logger = "0.7.1"
log = "0.4.8"
actix-web = "2.0.0"
actix-rt = "1.0.0"
actix-cors = "0.2.0"
bb8 = "0.4.0"
bb8-postgres = "0.4.0"
tokio-postgres = "0.5.3"
async-std = "1.5.0"
async-trait = "0.1.26"
testcontainers = "0.9.1"
lazy_static = "1.4.0"
actix-http = "1.0.1"
actix-service = "1.0.5"
bytes = "0.5.4"
serde_json = "1.0.50"
thiserror = "1.0.14"
rust-embed = "5.5.1"
uuid = "0.8.1"
chrono = "0.4.11"

[dev-dependencies]
galvanic-assert = "0.8.7"
assert-json-diff = "1.0.3"
rstest = "0.6.0"