[package]
name = "spacegame"
version = "0.1.0"
authors = ["Graham Cox <graham@grahamcox.co.uk>"]
edition = "2018"

[lib]
name = "spacegame_lib"

[[bin]]
name="spacegame"

[dependencies]
dotenv = "0.15.0"
serde = {version = "1.0.105", features=["derive"] }
config = "0.10.1"
env_logger = "0.7.1"
log = "0.4.8"
actix-web = "2.0.0"
actix-rt = "1.0.0"
actix-cors = "0.2.0"
bb8 = "0.4.0"
bb8-postgres = "0.4.0"
tokio-postgres = "0.5.3"
async-std = "1.5.0"

[dev-dependencies]
galvanic-assert = "0.8.7"