[package]
name = "spacegame"
version = "0.1.0"
authors = ["Graham Cox <graham@grahamcox.co.uk>"]
edition = "2018"

[lib]
name = "spacegame_lib"

[[bin]]
name="spacegame"

[dependencies]
dotenv = "0.15.0"
serde = {version = "1.0.105", features=["derive"] }
config = "0.10.1"
