version: "3"

services:
  spacegame-dev-postgres:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_DB: spacegame
      POSTGRES_USER: spacegame
      POSTGRES_PASSWORD: spacegame
    ports:
      - "127.0.0.1:45432:5432"
    networks:
      - spacegame-dev

  spacegame-dev-phppgadmin:
    image: dockage/phppgadmin:latest
    environment:
      - PHP_PG_ADMIN_SERVER_DESC=spacegame
      - PHP_PG_ADMIN_SERVER_HOST=spacegame-dev-postgres
      - PHP_PG_ADMIN_SERVER_PORT=5432
      - PHP_PG_ADMIN_SERVER_SSL_MODE=disable
      - PHP_PG_ADMIN_SERVER_DEFAULT_DB=spacegame
      - PHP_PG_ADMIN_SHOW_ADVANCED=true
      - PHP_PG_ADMIN_SHOW_COMMENTS=true
      - PHP_PG_ADMIN_OWNED_ONLY=true
      - PHP_PG_ADMIN_SHOW_SYSTEM=true
      - PHP_PG_ADMIN_SHOW_OIDS=true
    ports:
      - "127.0.0.1:48081:80"
    depends_on:
      - spacegame-dev-postgres
    networks:
      - spacegame-dev

networks:
  spacegame-dev:
